version: "3.6"
services:
  postgres:
    image: postgres:15.6-bullseye
    restart: always
    volumes:
      - ./.volumes/pg:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.38.1
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
